Cargo.toml
These were cargo culted from the ostree-ext code and are unused
there too.
=> Remove unused tokio-{stream,util} deps

Cargo.toml, src/imageproxy.rs
Take `&mut self` consistently
In order to implement proper error handling, we are going
to need to also access the singleton child process state.
(In the future we should support concurrent blob fetches
which would return the `std::fs::File` which can be accessed
concurrently/separately from the proxy.  But our users aren't
doing concurrent fetches yet)
---
Check for child exit during all requests
I am seeing the proxy seeming to exit during a request.  We
need to also monitor the child process while making a request.
---
Use main request method for semver checking
Previously I refactored the code to have `impl_request_raw`
to check the semver so we could do the child process checking
at the same time.  But now that that's a default part of the main
request flow, clean things up here make …
=> Fixes for child process monitoring

Cargo.toml, src/imageproxy.rs
Cargo.toml: Fix git repo link
---
Cargo.toml: Drop incorrect `dox` feature
This is only necessary for libraries like ostree-ext that have
a dependency on a C library.
---
Fix a few minor doc issues
---
=> minor fixes

src/imageproxy.rs
See https://github.com/tokio-rs/tokio/issues/3520
and https://gitlab.gnome.org/GNOME/glib/-/issues/1866#note_1310871
This is a workaround for tokio installing a global `SIGCHLD` handler,
which GLib *also* does.  It's then a Highlander situation.
Work around this by using the blocking API in std which internally
just uses `waitpid()`.
=> Switch to blocking in thread for child process wait

src/imageproxy.rs
This will allow higher level tooling to inject their own
sandboxing.
I would like to add opinionated usage of e.g. `systemd-run` but
this is a useful start.
=> Add an option to provide externally configured `Command`

Cargo.toml, src/imageproxy.rs
Rather than forking `setpriv` from `util-linux`, which on RHEL8 is too
old to understand `--pdeathsig`.  Motivated by having this work
out of the box on RHEL8.
=> Use `capctl` for `PR_SET_PDEATHSIG`

.github/workflows/ci.yaml
This adds two jobs in order to check minimum toolchain compatibility,
and for overall linting.
=> ci: add jobs for MSRV checks and linting

src/imageproxy.rs
We need this for a few reasons:
- It has the layer ordering, which we are *currently* ignoring
but will probably be important for correctness later
- It is the only thing that has extensible metadata that will
survive round trips through docker schema 2
=> imageproxy: Add a method to get image configuration

.github/workflows/ci.yaml, src/imageproxy.rs
Will help allow ostree pull images from internal registries
Helps https://github.com/ostreedev/ostree-rs-ext/issues/121
Also change authfile type from String to PathBuf
=> Add certificate_authority to expose --cert-dir

.github/workflows/ci.yaml
Now that https://github.com/ostreedev/ostree-rs-ext/pull/180
landed.  This completes the "ratcheting" we needed to do to land both
PRs.
=> ci: Reset back to main ostreedev branch

.github/workflows/ci.yaml, Cargo.toml, src/imageproxy.rs
I thought my initial code to dynamically detect the proxy
version was cool - it maximizes flexibility.  I think it is a pattern
we will want in the future.
However, what I realized when doing some work related to this in
ostree-ext is that for this particular API, we need to make it a hard
dependency.
So we might as well do the much simpler thing and make it a compile
time feature.  Then all we need to do is change the runtime code
to match on the build-time selected semver.
=> Use compile time rather than runtime detection for v0_2_3

Cargo.toml
This will avoid multiple versions in at least the rpm-ostree
dependency chain.
=> Bump to nix 0.23

.github/workflows/ci.yaml, Cargo.toml, src/imageproxy.rs
Unfortunately we need to temporarily disable our revdep CI
for this.
Bump the semver.
=> Hard require skopeo 1.6.0, use oci-spec in public API

.github/workflows/ci.yaml
This matches what we use in ostree now.
=> ci: Bump MSRV and lint toolchain

Cargo.toml
I saw this go by
https://www.reddit.com/r/rust/comments/v8e9fa/local_async_executors_and_why_they_should_be_the/
and I think it's a good argument why not to use the multithreaded
tokio by default.
=> Minimize `tokio` features

Cargo.toml, src/imageproxy.rs
Note `cargo fix --edition` did one change that is probably around
drop ordering.
=> Update to Rust 2021

Cargo.toml, src/imageproxy.rs
Specifically this binds `OpenImageOptional`.
=> Add support for proxy semver 0.2.4 API

src/imageproxy.rs
This API exposes the "GetLayerInfosForCopy" API in containers/image,
which can be used to create a mapping between blob and diff IDs,
allowing pulling via diffID.
Signed-off-by: RishabhSaini <rsaini@redhat.com>
=> Add get_layer_info_json

Cargo.toml, src/imageproxy.rs
Motivated by https://github.com/ostreedev/ostree-rs-ext/pull/413 which is in turn an adaption of code that lives in rpm-ostree today from https://github.com/coreos/rpm-ostree/commit/d661e8f974f8d2550a865c2866476160e333ec72 which aims to support privilege separation.
This doesn't lower privilege separation into this project (yet), just aids in passing data across boundaries.
=> Add support for passing auth creds via fd

.github/workflows/ci.yaml, Cargo.toml, src/imageproxy.rs
- Use `checkout@v3` to avoid deprecation warnings
- switch to https://github.com/dtolnay/rust-toolchain after seeing https://www.reddit.com/r/rust/comments/z1mlls/actionsrs_github_actions_need_more_maintainers_or/
- Re-enable ostree-ext reverse dependency testing
=> ci: Revamp

src/imageproxy.rs
Because we use this in our public APIs.
=> Re-export `oci-spec`

Cargo.toml, src/imageproxy.rs
Use rustix instead of capctl
In the interest in having fewer random crates in the
dependency graph.
---
Release 0.5.4
---
=> Use rustix instead of capctl && release

.github/workflows/ci.yaml, Cargo.toml, src/imageproxy.rs
proxy: Fix build with new nix `recvmsg` lifetimes
An updated nix fixes an incorrect lifetime.
cc https://github.com/nix-rust/nix/issues/2083
Signed-off-by: Colin Walters <walters@verbum.org>
---
build-sys: Bump MSRV to 1.63
Since rustix did.
Signed-off-by: Colin Walters <walters@verbum.org>
---
proxy: Fix a few stylistic clippy lints
Signed-off-by: Colin Walters <walters@verbum.org>
---
=> proxy: Fix build with new nix `recvmsg` lifetimes

.github/workflows/ci.yaml, Cargo.toml, src/imageproxy.rs
Support cap-std-ext 3.0 too
To make it easier to bump the deptree of everything to cap-std 2.0.
Signed-off-by: Colin Walters <walters@verbum.org>
---
Bump rust-version = 1.70
Since C9S has long since had it.
---
ci: Drop MSRV checks, merge fmt and linting
This aligns with https://github.com/ostreedev/ostree-rs-ext/commit/7650946cfac1eaa829d643e3d1d80c1d19a1a1bd
Basically clippy has a low signal/reward ratio by default.
---
=> Support cap-std-ext 3.0 too && CI updates

Cargo.toml, examples/client.rs
This is useful as a reference.
=> Add an example client

src/imageproxy.rs
This PR adds support for supplying the decryption keys to skopeo. 
Fixes: https://github.com/containers/containers-image-proxy-rs/issues/60
=> Add support for setting decryption keys

Cargo.toml
Because we're not affected by the cap-std API changes.
=> lib: Support cap-std-ext 4

Cargo.toml, src/imageproxy.rs
Update to the latest semver for oci-spec.  While we're here, switch to using the std OnceCell and drop the unused libc dependency.
=> Update oci-spec, drop once-cell and libc

.github/workflows/ci.yaml, Cargo.toml, ci/test-ostree-rs-ext.sh, examples/client.rs, src/imageproxy.rs
Now we can use a proper Digest type.
=> Port to oci-spec 0.7

Cargo.toml, src/imageproxy.rs
Same motivation as https://github.com/containers/ocidir-rs/pull/16
Originally I split this out as a "quick library" and using anyhow was convenient, but since we're bumping semver let's port to thiserror.
=> Port to thiserror, release 0.7

.github/workflows/ci.yaml
Signed-off-by: John Eckersberg <jeckersb@redhat.com>
=> ci: revert ostree-rs-ext back to ostreedev

src/imageproxy.rs
To aid debugging https://github.com/ostreedev/ostree-rs-ext/issues/657
This will be especially handy with https://github.com/containers/skopeo/pull/2439
=> Support using --debug with skopeo

src/imageproxy.rs
This commit adds a new SkopeoSpawnError that helps with tweaking the user-experience when e.g. skopeo is not installed.
Partially closes:
https://github.com/containers/composefs-rs/issues/59
=> imageproxy: introduce SkopeoSpawnError to improve UX

src/imageproxy.rs
Minor followup to the previous change; part of the idea of having the error types here is so we can *also* dig through the `SkopeoSpawnError` and precisely match against the `std::io::ErrorKind::NotFound`, and not rely on its stringified form. This is what we'd expect other callers to do.
This also avoids a double-match.
=> Change test case to match error via types, not strings

examples/client.rs
To aid in trying to reproduce the broken pipe errors we see sometimes in bootc.
=> examples: Add a thingy to fetch container to devnull

src/imageproxy.rs
The internal detail of how we handle the exit of the child process leads to the entire ImageProxy struct not being Send, which means that it can't be used in cross-thread Futures with tokio.  Fortunately it's a very simple fix.
Add some trivial static testing to make sure this doesn't regress.  Add it for OpenedImage as well: it's currently trivially Send+Sync on account of being a wrapper around an integer, but this might change in the future.
This change has been cross-checked against both bootc (ostree-ext) and composefs-rs and doesn't cause any issues.
=> imageproxy: make ImageProxy: Send + Sync

src/imageproxy.rs
See https://github.com/bootc-dev/bootc/issues/1284 - the error text is
`ERROR Upgrading: Creating importer: failed to invoke method OpenImage: failed to invoke method OpenImage: lstat ...`
This fixes the duplication of `failed to invoke method OpenImage`.
I think this was a regression from porting to use thiserror when I was changing the type of each individual function to return our Result type.
=> proxy: Drop double-wrapping in `RequestInitiationError`

Cargo.toml
And we now hard require >= 0.8.2.
xref https://github.com/youki-dev/oci-spec-rs/pull/288
=> Bump semver due to incompatible oci-spec change

Cargo.toml, src/imageproxy.rs
=> tests: Add a failing test case for OpenImageOptional with oci-archive

src/imageproxy.rs
The internal API in containers/image returns a size...which is an `int64` in the source probably because OCI Descriptor type have it be an int64 too for bad historical reasons; xref https://github.com/opencontainers/image-spec/pull/153
Anyways, the `GetBlob` wrapper API returns `-1` when the remote registry doesn't emit `Content-Length`: https://github.com/containers/container-libs/blob/3af9abd27f3b875122b9fedd88953e8c840d6958/image/docker/docker_client.go#L1068
And this apparently happens with at least the Quay mirror registry.
We also noticed this problem when adding `GetRawBlob` in https://github.com/containers/skopeo/pull/2601
which simply doesn't return a size to the client at all.
=> Ignore size value from GetBlob

src/imageproxy.rs
Just like GetBlob, the size might not be known. In the case of this API, one use case is being driven from e.g. https://github.com/cgwalters/cstor-dist
which is exposing a HTTP API, so it's really useful for us to have the size here so that server can in turn provide it via its own `Content-Length` if available.
=> get_raw_blob: Properly handle -1 return from GetRawBlob
